name: Deploy to GitHub Pages

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write
      contents: read
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.11.0
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build project
      run: npm run vite-build
      
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
        
    - name: Preserve CNAME file
      run: |
        if [ -f gh-pages/CNAME ]; then
          cp gh-pages/CNAME dist/CNAME
        fi
        
    - name: Deploy to gh-pages branch
      run: |
        cd gh-pages
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Sync files from dist to current directory
        # This will only modify files that are actually different
        rsync -av --delete --exclude='.git' ../dist/ ./
        
        # Add all changes
        git add .
        
        # Commit if there are changes
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Deploy from commit ${{ github.sha }}"
          git push origin gh-pages
        else
          echo "No changes to deploy"
        fi